{
  description = "Kiskaadee's Modular NixOS Configuration";

  # --- External Repositories & Flake Inputs ---
  # These inputs specify where Nix downloads package sets, tools, and configurations.
  inputs = {
    # NixOS Unstable channel - used for bleeding-edge package releases
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    # Home Manager - manages user-space configurations, dotfiles, and shell environments
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs"; # Forces home-manager to use the same nixpkgs channel
    };

    # DankMaterialShell (DMS) - core custom desktop shell environment and panel
    dms = {
      url = "github:AvengeMedia/DankMaterialShell";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # dgop - companion system monitoring / daemon utility for DankMaterialShell
    dgop = {
      url = "github:AvengeMedia/dgop";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # dank-greeter - greetd login screen with Dank Material aesthetic
    dank-greeter = {
      url = "github:AvengeMedia/dank-greeter";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # DankCalendar - calendar daemon and UI for DMS
    dankcalendar = {
      url = "github:AvengeMedia/dankcalendar";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # DankSearch - fast indexed filesystem search for DMS
    danksearch = {
      url = "github:AvengeMedia/danksearch";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Zen Browser - modern, lightweight, community-maintained browser
    zen-browser = {
      url = "github:0xc000022070/zen-browser-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    ## Cryptographic Secrets management
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
      };

    # Antigravity CLI - coding companion and local AI agent helper
    antigravity = {
      url = "github:jacopone/antigravity-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  # --- System Outputs (Configuration Definitions) ---
  # Maps host machines to target environments, architecture types, and user settings.
  outputs = { self, nixpkgs, home-manager, dms, dgop, dank-greeter, dankcalendar, danksearch, zen-browser, antigravity, ...}@inputs: {
    nixosConfigurations = {
      
      # 🌐 SERVER HOST (Dedicated Headless Homelab Node)
      # Production server host running Docker, Traefik, SOPS secrets, and DDNS.
      server = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit inputs; };
        modules = [
          ./hosts/server/hardware-configuration.nix
          ./hosts/server/configuration.nix
          inputs.sops-nix.nixosModules.sops

          home-manager.nixosModules.home-manager {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "backup";
            home-manager.extraSpecialArgs = { inherit inputs; };
            home-manager.users.kiskaadee = {
              imports = [
                ./home.nix
                ./hosts/server/home.nix
              ];
            };
          }
        ];
      };

      # 🖥️ DESKTOP HOST (Legacy Dual-Mode Workstation)
      # Workstation running Hyprland with specialisation fallback.
      desktop = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit inputs; }; # Pass flake inputs into submodules (e.g. system/base.nix)
        modules = [
          ./hosts/desktop/hardware-configuration.nix # Autogenerated hardware/disk/CPU module
          ./hosts/desktop/configuration.nix          # Desktop environment / system package settings
          inputs.sops-nix.nixosModules.sops          # Import Sops module
          inputs.dank-greeter.nixosModules.default   # Import Dank Greeter module
          inputs.dankcalendar.nixosModules.default   # Import Dank Calendar module

          home-manager.nixosModules.home-manager {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "backup"; # Auto-back up conflicting files
            home-manager.extraSpecialArgs = { inherit inputs; };
            home-manager.users.kiskaadee = {
              imports = [
                ./home.nix
                ./hosts/desktop/home.nix
                inputs.danksearch.homeModules.default
              ];
            };
          }
        ];
      };

      # 💻 LAPTOP HOST (Mobile Workstation)
      # Target laptop workstation running Niri window manager.
      laptop = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit inputs; };
        modules = [
          ./hosts/laptop/hardware-configuration.nix
          ./hosts/laptop/configuration.nix
          inputs.dank-greeter.nixosModules.default
          inputs.dankcalendar.nixosModules.default

          home-manager.nixosModules.home-manager {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "backup"; # Auto-back up conflicting files
            home-manager.extraSpecialArgs = { inherit inputs; };
            home-manager.users.kiskaadee = {
              imports = [
                ./home.nix
                ./hosts/laptop/home.nix
                inputs.danksearch.homeModules.default
              ];
            };
          }
        ];
      };
    };
  };
}
