{
  description = "Kiskaadee's Modular NixOS Configuration";

  # --- External Repositories & Flake Inputs ---
  # These inputs specify where Nix downloads package sets, tools, and configurations.
  inputs = {
    # NixOS Unstable channel - used for bleeding-edge package releases
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    # Home Manager - manages user-space configurations, dotfiles, and shell environments
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs"; # Forces home-manager to use the same nixpkgs channel
    };

    # DankMaterialShell (DMS) - core custom desktop shell environment and panel
    dms = {
      url = "github:AvengeMedia/DankMaterialShell";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # dgop - companion system monitoring / daemon utility for DankMaterialShell
    dgop = {
      url = "github:AvengeMedia/dgop";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Zen Browser - modern, lightweight, community-maintained browser
    zen-browser = {
      url = "github:0xc000022070/zen-browser-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    ## Cryptographic Secrets management
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
      };

    # Antigravity CLI - coding companion and local AI agent helper
    antigravity = {
      url = "github:jacopone/antigravity-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  # --- System Outputs (Configuration Definitions) ---
  # Maps host machines to target environments, architecture types, and user settings.
  outputs = { self, nixpkgs, home-manager, dms, dgop, zen-browser, antigravity, ...}@inputs: {
    nixosConfigurations = {
      
      # 🖥️ DESKTOP HOST
      # Target workstation running Hyprland as the window manager.
      desktop = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit inputs; }; # Pass flake inputs into submodules (e.g. system/base.nix)
        modules = [
          ./hosts/desktop/hardware-configuration.nix # Autogenerated hardware/disk/CPU module
          ./hosts/desktop/configuration.nix          # Desktop environment / system package settings
          inputs.sops-nix.nixosModules.sops          # Import Sops module

          home-manager.nixosModules.home-manager {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "backup"; # Auto-back up conflicting files
            home-manager.extraSpecialArgs = { inherit inputs; };
            home-manager.users.kiskaadee = {
              imports = [
                ./home.nix
                ./hosts/desktop/home.nix
              ];
            };
          }
        ];
      };

      # 💻 LAPTOP HOST
      # Target laptop workstation. Intended to run Niri window manager.
      # Shares modules/ base, but customizes graphical desktop components.
      laptop = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit inputs; };
        modules = [
          ./hosts/laptop/hardware-configuration.nix
          ./hosts/laptop/configuration.nix

          home-manager.nixosModules.home-manager {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "backup"; # Auto-back up conflicting files
            home-manager.extraSpecialArgs = { inherit inputs; };
            home-manager.users.kiskaadee = {
              imports = [
                ./home.nix
                ./hosts/laptop/home.nix
              ];
            };
          }
        ];
      };
    };
  };
}
