# General configuration
syslog=no
pid=/run/ddclient/ddclient.pid
cache=/var/lib/ddclient/ddclient.cache
usev4=webv4

# Provider definition using credentials decrypted at runtime
protocol=dyndns2
server=api.dynu.com
login=@dynu_user@
password=@dynu_password@
@dynu_domain@
